// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB49bQmO79YZkkzyiEcruFAv221F7Rb_yM',
    appId: '1:614677913162:android:ee0b08a878bb55fec650b3',
    messagingSenderId: '614677913162',
    projectId: 'speedbrakerfinal',
    storageBucket: 'speedbrakerfinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWYljyv7gLXVteT49xX8jIP4Jv09lHKQY',
    appId: '1:614677913162:ios:6892151b7ce4dbeec650b3',
    messagingSenderId: '614677913162',
    projectId: 'speedbrakerfinal',
    storageBucket: 'speedbrakerfinal.appspot.com',
    androidClientId: '614677913162-7euhhj91oc1nvrbu3c46jtsjaqlm43ln.apps.googleusercontent.com',
    iosClientId: '614677913162-ba4o4o310geht1ut7igktan8lto5u29j.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingIsolate',
  );
}
